/**
 * @author Ján Kertis <kertis.jan.15@gmail.com>
 * @copyright Ján Kertis, 2016
 */

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE';

export const SEARCH_VENUES_REQUEST = 'SEARCH_VENUES_REQUEST';
export const SEARCH_VENUES_SUCCESS = 'SEARCH_VENUES_SUCCESS';
export const SEARCH_VENUES_FAILURE = 'SEARCH_VENUES_FAILURE';

export const SEARCH_FOOD_REQUEST = 'SEARCH_FOOD_REQUEST';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAILURE = 'SEARCH_FOOD_FAILURE';

export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const ADD_PLACE_FAILURE = 'ADD_PLACE_FAILURE';

export const VOTE_UP_REQUEST = 'VOTE_UP_REQUEST';
export const VOTE_UP_SUCCESS = 'VOTE_UP_SUCCESS';
export const VOTE_UP_FAILURE = 'VOTE_UP_FAILURE';
